# Generated by Django 5.0 on 2024-01-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('has_been_answered', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
