# Generated by Django 5.0 on 2023-12-24 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_faq_question_alter_faqcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlisting',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='list_content', to='administrator.project'),
            preserve_default=False,
        ),
    ]
