# Generated by Django 5.0 on 2023-12-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_projectlisting_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_been_answered',
            field=models.BooleanField(default=False),
        ),
    ]
