# Generated by Django 5.0 on 2024-01-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_client_has_been_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestservice',
            name='image2',
            field=models.CharField(default='/home.jpg', max_length=150),
            preserve_default=False,
        ),
    ]
