# Generated by Django 5.0 on 2024-01-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_requestservice_image2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
