// projectsData.js

const projectsData = [
    {
      id: 1,
      projectTitle: "Modern Office Renovation",
      image: "/project1.jpg",
      clientName: "ABC Corporation",
      location: "City Center, New York",
      date: "2023-05-15",
      website: "http://www.abccorporation.com",
      projectDetails: "A comprehensive renovation project focusing on creating a dynamic and collaborative workspace. The design incorporates sleek aesthetics, state-of-the-art technology, and ergonomic furnishings to enhance employee productivity and well-being.",
      listContent: [
        "Open workspace layout",
        "Smart lighting solutions",
        "Tech-integrated meeting rooms",
      ],
      projectDetails2: "Integration of Sustainable Practices",
      listContent2: [
        "Energy-efficient HVAC systems",
        "Recycled and eco-friendly materials",
        "Green rooftop garden",
      ],
    },
    {
      id: 2,
      projectTitle: "E-commerce Website Development",
      image: "/project2.jpg",
      clientName: "XYZ Retailers",
      location: "Online",
      date: "2023-07-20",
      website: "http://www.xyzretailers.com",
      projectDetails: "A complex e-commerce development project focused on delivering a seamless online shopping experience. The website features a user-friendly interface, secure payment gateways, and robust inventory management to support the client's growing online retail business.",
      listContent: [
        "Product catalog with categories",
        "User account management",
        "Integration with payment gateways",
      ],
      projectDetails2: "Mobile App Integration",
      listContent2: [
        "Cross-platform mobile app",
        "Push notifications for promotions",
        "User-friendly checkout process",
      ],
    },
    {
      id: 3,
      projectTitle: "Community Park Revitalization",
      image: "/project.jpg",
      clientName: "City Municipality",
      location: "Green Valley Suburb",
      date: "2023-08-30",
      website: "http://www.citymunicipality.gov",
      projectDetails: "A community-focused initiative to revitalize an existing park. The project includes the installation of new playground equipment, creation of walking and jogging trails, and the development of dedicated areas for picnics and relaxation. The goal is to promote community engagement and a healthier lifestyle.",
      listContent: [
        "New playground equipment",
        "Walking and jogging trails",
        "Picnic and relaxation areas",
      ],
      projectDetails2: "Environmental Sustainability",
      listContent2: [
        "Planting native trees and plants",
        "Solar-powered lighting",
        "Water conservation measures",
      ],
    },
    {
      id: 4,
      projectTitle: "High-Tech Research Facility",
      image: "/project.jpg",
      clientName: "Tech Innovations Ltd.",
      location: "Tech Hub City",
      date: "2023-10-12",
      website: "http://www.techinnovations.com",
      projectDetails: "Construction of a cutting-edge research facility equipped with state-of-the-art laboratories and collaborative spaces. The design emphasizes technological advancements, energy efficiency, and a conducive environment for breakthrough innovations.",
      listContent: [
        "Specialized research laboratories",
        "Collaboration zones",
        "High-speed data infrastructure",
      ],
      projectDetails2: "Technological Integration",
      listContent2: [
        "Advanced security systems",
        "Smart climate control",
        "Collaborative virtual environments",
      ],
    },
    {
      id: 5,
      projectTitle: "Luxury Residential Complex",
      image: "/project.jpg",
      clientName: "Elite Residences Ltd.",
      location: "Prime Residential Area",
      date: "2023-11-28",
      website: "http://www.eliteresidences.com",
      projectDetails: "Development of an exclusive residential complex featuring luxurious apartments and world-class amenities. The design focuses on creating a sophisticated and comfortable living experience for residents seeking opulence and convenience.",
      listContent: [
        "Spacious and elegant apartments",
        "Private balconies with scenic views",
        "Resort-style swimming pool",
      ],
      projectDetails2: "Premium Lifestyle Services",
      listContent2: [
        "Concierge services",
        "Fitness and wellness center",
        "Fine dining restaurant",
      ],
    },
    {
      id: 6,
      projectTitle: "Cultural Arts Center",
      image: "/project.jpg",
      clientName: "City Arts Council",
      location: "Downtown Cultural District",
      date: "2024-02-15",
      website: "http://www.cityarts.org",
      projectDetails: "Construction of a state-of-the-art cultural arts center dedicated to fostering creativity and showcasing diverse forms of artistic expression. The design incorporates versatile performance spaces, exhibition halls, and studios to support the local arts community.",
      listContent: [
        "Main auditorium for performances",
        "Gallery spaces for exhibitions",
        "Artists-in-residence studios",
      ],
      projectDetails2: "Community Engagement Programs",
      listContent2: [
        "Art workshops and classes",
        "Cultural festivals and events",
        "Collaborations with local artists",
      ],
    },
    {
      id: 7,
      projectTitle: "Hospital Expansion Project",
      image: "/project.jpg",
      clientName: "City Health Network",
      location: "Medical District",
      date: "2024-04-05",
      website: "http://www.cityhealthnetwork.org",
      projectDetails: "Expansion and renovation of a major hospital facility to meet the growing healthcare needs of the community. The project includes the addition of specialized medical wings, modernized patient rooms, and enhanced medical technology infrastructure.",
      listContent: [
        "Cardiology and oncology wings",
        "Upgraded surgical suites",
        "Advanced medical imaging facilities",
      ],
      projectDetails2: "Patient-Centric Approach",
      listContent2: [
        "Comfortable and healing environments",
        "Patient-focused care models",
        "Integration of digital health records",
      ],
    },
    {
      id: 8,
      projectTitle: "Sustainable Urban Development",
      image: "/project.jpg",
      clientName: "Urban Development Authority",
      location: "City Redevelopment Zone",
      date: "2024-06-20",
      website: "http://www.urbandevelopment.org",
      projectDetails: "An urban redevelopment project focused on creating a sustainable and livable urban environment. The design includes green spaces, eco-friendly infrastructure, and mixed-use developments to support a diverse and vibrant community.",
      listContent: [
        "Green roofs and public parks",
        "Mixed-use commercial and residential buildings",
        "Eco-friendly transportation options",
      ],
      projectDetails2: "Community Resilience Initiatives",
      listContent2: [
        "Community gardens and urban farming",
        "Resilience workshops and training",
        "Smart city technologies",
      ],
    },
  ];
  
  export default projectsData;
  