// servicesData.js

const servicesData = [
    {
      id: 1,
      title: "Financial Consultancy",
      heading1: "Why Us For International Business Management Consulting!",
      content1:
        "Completely synergized resourced taxings relationships premiers markets ultivate one-to-one customer service with robust ideas dynamically innovated resources leveling customer service for state of the art customer service innovate product for reliable supply engage web services cutting-edge deliverables.",
      heading2: "Proactively Envisioned Multimedia Based Expertise Media Growth Superior Collaboration",
      content2:
        "One-to-one customer service with robust ideas dynamically innovated resources for reliable supply engage web services cutting-edge deliverables.",
      heading3: "Our Benefits",
      subheading: "Incubate standards compliant channels benefits.",
      listContent: [
        "Credibly reintermediate backend",
        "Holistically foster superior",
        "Distinctively exploit optimal",
      ],
      content1heading1: "Financial Consultancy",
      image: "/home.jpg",
      image1: "/home.jpg",
    },
    {
      id: 2,
      title: "IT Consultancy",
      heading1: "Strategic IT Consulting",
      content1:
        "Proactive IT consulting services to align your IT strategy with business goals. Our experts provide insights and recommendations to optimize your IT infrastructure and enhance overall efficiency.",
      heading2: "Innovative Solutions for IT Challenges",
      content2:
        "We offer innovative solutions to address your IT challenges, ensuring that your technology supports your business objectives. Stay ahead in the fast-paced world of technology with our expert guidance.",
      heading3: "Our Services",
      subheading: "Comprehensive IT consultancy services tailored to your needs.",
      listContent: [
        "Custom software development",
        "Network infrastructure design",
        "IT security and risk management",
      ],
      content1heading1: "IT Consultancy",
      image: "/home.jpg",
      image1: "/home.jpg",
    },
    {
      id: 3,
      title: "Networking Solutions",
      heading1: "Efficient Networking Solutions",
      content1: "Streamlined networking solutions for seamless communication and data transfer.",
      heading2: "Scalable Infrastructure",
      content2: "Build scalable and robust network infrastructure tailored to your organization's needs.",
      heading3: "Key Features",
      subheading: "Enhance connectivity and collaboration with our networking solutions.",
      listContent: [
        "High-speed data transfer",
        "Secure network architecture",
        "24/7 network monitoring",
      ],
      content1heading1: "Networking Solutions",
      image: "/home.jpg",
      image1: "/home.jpg",
    },
    {
      id: 4,
      title: "Website Design & Application Development",
      heading1: "Creative Website Design",
      content1: "Captivate your audience with visually stunning and user-friendly website designs.",
      heading2: "Custom Application Development",
      content2: "Develop custom applications that align with your business goals and user requirements.",
      heading3: "Our Solutions",
      subheading: "Elevate your online presence with our website and application development services.",
      listContent: [
        "Responsive web design",
        "E-commerce development",
        "Mobile app development",
      ],
      content1heading1: "Website Design & App Development",
      image: "/home.jpg",
      image1: "/home.jpg",
    },
    {
      id: 5,
      title: "Mobile Design & Application Development",
      heading1: "Mobile-First Design",
      content1: "Craft engaging and intuitive mobile experiences with our mobile-first design approach.",
      heading2: "Cross-Platform App Development",
      content2: "Develop versatile applications that run seamlessly on multiple platforms.",
      heading3: "Our Expertise",
      subheading: "Empower your business with our mobile design and application development services.",
      listContent: [
        "iOS and Android development",
        "User interface design",
        "App testing and optimization",
      ],
      content1heading1: "Mobile Design & App Development",
      image: "/home.jpg",
      image1: "/home.jpg",
    },
    {
      id: 6,
      title: "Sales and Repairs of Laptops & Desktops",
      heading1: "Laptop and Desktop Solutions",
      content1: "Trust our experts for reliable sales, repairs, and maintenance of laptops and desktops.",
      heading2: "Quick and Efficient Repairs",
      content2: "Get your devices back in optimal condition with our quick and efficient repair services.",
      heading3: "Our Services",
      subheading: "Ensure the longevity and performance of your devices with our sales and repair solutions.",
      listContent: [
        "Laptop sales and customization",
        "Desktop repairs and upgrades",
        "Virus and malware removal",
      ],
      content1heading1: "Sales and Repairs of Laptops & Desktops",
      image: "/home.jpg",
      image1: "/home.jpg",
    },
    {
      id: 7,
      title: "CCTV Camera Installation and Maintenance",
      heading1: "Secure Your Space with CCTV",
      content1: "Install CCTV cameras for enhanced security and surveillance of your premises.",
      heading2: "Regular Maintenance Services",
      content2: "Ensure the continued functionality of your CCTV system with our maintenance services.",
      heading3: "Key Features",
      subheading: "Protect your property with our comprehensive CCTV camera installation and maintenance.",
      listContent: [
        "HD camera installation",
        "Remote monitoring services",
        "Motion detection and alerts",
      ],
      content1heading1: "CCTV Camera Installation",
      image: "/home.jpg",
      image1: "/home.jpg",
    },
    {
      id: 8,
      title: "Data Recovery (From Crashed/Formatted Hard drive)",
      heading1: "Expert Data Recovery",
      content1: "Trust our specialists to recover your valuable data from crashed or formatted hard drives.",
      heading2: "State-of-the-Art Recovery Techniques",
      content2: "Utilize advanced techniques to retrieve lost data and restore it to its original state.",
      heading3: "Our Process",
      subheading: "Regain access to your crucial data with our professional data recovery services.",
      listContent: [
        "Hard drive diagnostics",
        "File extraction and restoration",
        "Preventative data backup solutions",
      ],
      content1heading1: "Data Recovery Services",
      image: "/home.jpg",
      image1: "/home.jpg",
    },
    {
      id: 9,
      title: "General IT Services",
      heading1: "Comprehensive IT Solutions",
      content1: "Explore a range of general IT services designed to meet the diverse needs of your business.",
      heading2: "Tailored Solutions",
      content2: "Receive personalized solutions that address your specific IT challenges and requirements.",
      heading3: "Our Offerings",
      subheading: "Partner with us for reliable and efficient general IT services.",
      listContent: [
        "IT infrastructure management",
        "Help desk and support services",
        "Software installation and updates",
      ],
      content1heading1: "General IT Services",
      image: "/home.jpg",
      image1: "/home.jpg",
    },
    {
      id: 10,
      title: "Printing & Designing",
      heading1: "Quality Printing and Design",
      content1: "Experience top-notch printing and designing services that make your brand stand out.",
      heading2: "Custom Design Solutions",
      content2: "Collaborate with our designers to create custom designs that align with your brand identity.",
      heading3: "Our Services",
      subheading: "Enhance your brand image with our professional printing and designing services.",
      listContent: [
        "Business card printing",
        "Brochure and flyer design",
        "Large format printing",
      ],
      content1heading1: "Printing & Designing",
      image: "/home.jpg",
      image1: "/home.jpg",
    },
    {
      id: 11,
      title: "Solar and Inverter System",
      heading1: "Green Energy Solutions",
      content1: "Harness the power of solar and inverter systems for sustainable and efficient energy solutions.",
      heading2: "Custom Solar Installations",
      content2: "Design and install solar solutions tailored to your energy consumption and needs.",
      heading3: "Key Benefits",
      subheading: "Switch to renewable energy with our solar and inverter system services.",
      listContent: [
        "Solar panel installations",
        "Inverter system maintenance",
        "Energy efficiency consultations",
      ],
      content1heading1: "Solar and Inverter System",
      image: "/home.jpg",
      image1: "/home.jpg",
    },
  ];
  
  export default servicesData;
  